### ISSUE TITLE
Material Selection In parts.yaml?

### ISSUE THREAD

**Issue by jmwright** [modelb-llc/dof-helpers#3]
I have a project that uses a wooden dowel rod. Any light-weight rod will do if it's the right diameter and is stiff enough, but other than the notes in `parts.yaml`, I noticed that there is nowhere to specify metadata about the part like material, dimensions, etc. This is especially important if the part is COTS. I could encode wooden_dowel_rod and pvc_pipe as options, but other than building it into the names and descriptions there's no material designation.

**Comment by jmwright** [comment]
Something that MIGHT be related to this is infill with 3D printed parts. How do I tell a user that they must select at least 50% infill for a print? It seems like there needs to be the ability to specify metadata, but I'm not sure how everything would work together.

**Comment by modelb-jrs** [comment]
Some of this is covered over in issue #4.  

Regarding the parts list.  Here is what I would do to define a 12 inch long 1/4 inch diameter rod (based on how I handled [filament in trrs-wssm](https://github.com/modelb-llc/trrs-wssm/blob/master/components/trrs-wssm-housing-base/parts.yaml).

```
rod:
  id: rod
  description: Light-weight Rod
  quantity: 12
  quantityUnits: inches
  options:
  - _0_25-inch-diameter-wooden-dowel
  - _0_25_inch-diameter-pvc-pipe
  selectedOption: 0
  notes: Any other sufficiently stiff and light-weight material of the correct diameter may be substituted for the options listed here.
```

As for specifying infill, I think it is better to specify an exact amount (55% instead of at least 50%).  The reasons for that opinion include:

* Reduces ambiguity in the specification
* Enables accurate specification of required material quantity (there should not be a quantity of at least 10g)
* Moves specification of process (set slicer settings to 55% infill) to the assembly instructions where process details belong

In fact, I should have specified the percent infill in [these assembly steps](https://github.com/modelb-llc/trrs-wssm/blob/master/components/trrs-wssm-housing-base/assemblySteps.yaml), but I have been more focused on transferring existing specifications to SR from ODE instead of improving the specifications themselves.
